CHG: Use threads instead of processes in LocalCluster
- For some reason, creating a LocalCluster with processes=True reproducibly
  crashes Dask both on HPX and locally:
	tornado.util.TimeoutError: Worker failed to start
  Using thread-based parallelization seems to work (somewhat) but tornado
  keeps rocking the boat...

Changes to be committed:
	modified:   .gitignore
	modified:   spykewave/examples/ex_mtmfft.py